/* Import modules */
import { Ship } from './ship.js'
import { GameBoard } from './game-board.js'
import { Player } from './player.js'

/* Import DOM controller functions */
import {
  renderHumanGameBoard,
  renderComputerGameBoard,
  displayPlayerTurn,
  updatePlayerTurn,
  handleRepeatHit,
  handleDragStart,
  handleDragEnd,
  handleDragEnter,
  handleDragLeave,
  handleDragOver,
  handleDrop,
  updateShipDirection,
  displayWelcomeMessage,
  displayStartGameMessage,
  flashMessagesBackground,
  displayAIMessage,
  isHumanShipSunk,
  isComputerShipSunk,
  displayWinner,
  disableComputerGameBoard,
  enableComputerGameBoard,
  disablePlayButton,
  enablePlayButton,
  clearAllMessages,
  resetShipNames,
  disableResetButton,
  enableResetButton,
  disableRandomizeButton,
  enableRandomizeButton,
  clearPlayerTurn,
  styleStandardButton,
  unstyleStandardButton,
  styleAdvancedButton,
  unstyleAdvancedButton,
  addHoverEffect,
  disableHoverEffect,
  enableHumanGameBoard,
  disableHumanGameBoard,
  disableStandardButton,
  enableStandardButton,
  disableAdvancedButton,
  enableAdvancedButton,
} from './dom-controller.js'

/* Import game controller functions */
import {
  populateHumanGameBoard,
  populateComputerGameBoard,
  changeShipDirection,
  generateAdjacentShipCoordinates,
  generateRandomCoordinates,
} from './game-controller.js'

/* Import state functions */
import {
  setComputerLevel,
  getComputerLevel,
  getFirstClick,
  setFirstClick,
  setAdjacentCoordinates,
  getAdjacentCoordinates,
} from './state.js'

/* Import players */
import { humanPlayer, computerPlayer } from './players.js'

/* Export modules */
export {
  Ship,
  GameBoard,
  Player,
  humanPlayer,
  computerPlayer,
  renderHumanGameBoard,
  renderComputerGameBoard,
  displayPlayerTurn,
  updatePlayerTurn,
  handleRepeatHit,
  populateHumanGameBoard,
  populateComputerGameBoard,
  handleDragStart,
  handleDragEnd,
  handleDragEnter,
  handleDragLeave,
  handleDragOver,
  handleDrop,
  updateShipDirection,
  changeShipDirection,
  generateAdjacentShipCoordinates,
  generateRandomCoordinates,
  displayWelcomeMessage,
  displayStartGameMessage,
  flashMessagesBackground,
  displayAIMessage,
  isHumanShipSunk,
  isComputerShipSunk,
  displayWinner,
  disableComputerGameBoard,
  enableComputerGameBoard,
  disableResetButton,
  enableResetButton,
  disableRandomizeButton,
  enableRandomizeButton,
  disablePlayButton,
  enablePlayButton,
  clearAllMessages,
  resetShipNames,
  clearPlayerTurn,
  styleStandardButton,
  unstyleStandardButton,
  styleAdvancedButton,
  unstyleAdvancedButton,
  addHoverEffect,
  disableHoverEffect,
  enableHumanGameBoard,
  disableHumanGameBoard,
  disableStandardButton,
  enableStandardButton,
  disableAdvancedButton,
  enableAdvancedButton,
  setComputerLevel,
  getComputerLevel,
  getFirstClick,
  setFirstClick,
  setAdjacentCoordinates,
  getAdjacentCoordinates,
}
